### ISSUE TITLE
WeeWooWeeWoo

### ISSUE THREAD

**Issue by anujdhannawat** [zonetecde/random-github-repo#2]
I want to - 
1. Remove the duplicate <meta name="description"> tag.
2. Keep the %PUBLIC_URL% placeholders intact assuming you're using a build system that handles these correctly.

**Comment by zonetecde** [comment]
Thank you for your contribution, but this project is no longer active. The new website is [Random Github Repo 2](https://www.randomgithubrepo.site/), and the new GitHub repository is [this one](https://github.com/zonetecde/random-github-repo-2).
